-- ProApp Service Marketplace Database
-- Oracle SQL
-- This project uses entirely sample data.

CREATE TABLE CUSTOMER (
    CUSTOMERID       NUMBER PRIMARY KEY,
    NAME             VARCHAR2(100) NOT NULL,
    PHONE            VARCHAR2(20),
    EMAIL            VARCHAR2(100) NOT NULL,
    ADDRESS          VARCHAR2(255),
    MEMBERSHIP_TYPE  VARCHAR2(50) NOT NULL,

    CONSTRAINT UQ_CUSTOMER_EMAIL
        UNIQUE (EMAIL),

    CONSTRAINT CK_CUSTOMER_MEMBERSHIP
        CHECK (MEMBERSHIP_TYPE IN ('Basic', 'Premium'))
);

CREATE TABLE TASK (
    TASKID       NUMBER PRIMARY KEY,
    CUSTOMERID   NUMBER NOT NULL,
    TASK_TYPE    VARCHAR2(100) NOT NULL,
    BUDGET       NUMBER(10, 2) NOT NULL,
    STATUS       VARCHAR2(50) NOT NULL,
    TASK_DATE    DATE NOT NULL,

    CONSTRAINT FK_TASK_CUSTOMER
        FOREIGN KEY (CUSTOMERID)
        REFERENCES CUSTOMER(CUSTOMERID),

    CONSTRAINT CK_TASK_BUDGET
        CHECK (BUDGET >= 0),

    CONSTRAINT CK_TASK_STATUS
        CHECK (STATUS IN ('Open', 'Completed')),

    CONSTRAINT UQ_TASK_CUSTOMER
        UNIQUE (TASKID, CUSTOMERID)
);

CREATE TABLE TRADESPERSON (
    TRADESPERSONID  NUMBER PRIMARY KEY,
    NAME            VARCHAR2(100) NOT NULL,
    PHONE           VARCHAR2(20),
    EMAIL           VARCHAR2(100) NOT NULL,
    ADDRESS         VARCHAR2(255),
    SKILLS          VARCHAR2(255) NOT NULL,
    SKILL_LEVEL     VARCHAR2(50) NOT NULL,

    CONSTRAINT UQ_TRADESPERSON_EMAIL
        UNIQUE (EMAIL),

    CONSTRAINT CK_TRADESPERSON_LEVEL
        CHECK (
            SKILL_LEVEL IN (
                'Beginner',
                'Intermediate',
                'Expert',
                'Master'
            )
        )
);

CREATE TABLE BID (
    BIDID            NUMBER PRIMARY KEY,
    TASKID           NUMBER NOT NULL,
    TRADESPERSONID   NUMBER NOT NULL,
    BID_AMOUNT       NUMBER(10, 2) NOT NULL,
    BID_DATE         DATE NOT NULL,

    CONSTRAINT FK_BID_TASK
        FOREIGN KEY (TASKID)
        REFERENCES TASK(TASKID),

    CONSTRAINT FK_BID_TRADESPERSON
        FOREIGN KEY (TRADESPERSONID)
        REFERENCES TRADESPERSON(TRADESPERSONID),

    CONSTRAINT CK_BID_AMOUNT
        CHECK (BID_AMOUNT >= 0),

    CONSTRAINT UQ_BID_TASK_TRADE
        UNIQUE (TASKID, TRADESPERSONID)
);

CREATE TABLE PAYMENT_TRANSACTION (
    TRANSACTIONID    NUMBER PRIMARY KEY,
    TASKID           NUMBER NOT NULL,
    CUSTOMERID       NUMBER NOT NULL,
    AMOUNT           NUMBER(10, 2) NOT NULL,
    PAYMENT_METHOD   VARCHAR2(50) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,

    CONSTRAINT FK_PAYMENT_CUSTOMER
        FOREIGN KEY (CUSTOMERID)
        REFERENCES CUSTOMER(CUSTOMERID),

    CONSTRAINT FK_PAYMENT_TASK
        FOREIGN KEY (TASKID)
        REFERENCES TASK(TASKID),

    CONSTRAINT FK_PAYMENT_TASK_CUSTOMER
        FOREIGN KEY (TASKID, CUSTOMERID)
        REFERENCES TASK(TASKID, CUSTOMERID),

    CONSTRAINT CK_PAYMENT_AMOUNT
        CHECK (AMOUNT >= 0),

    CONSTRAINT CK_PAYMENT_METHOD
        CHECK (
            PAYMENT_METHOD IN (
                'Credit Card',
                'Debit Card',
                'e-Wallet'
            )
        )
);

CREATE TABLE RATING (
    RATINGID         NUMBER PRIMARY KEY,
    TASKID           NUMBER NOT NULL,
    CUSTOMERID       NUMBER NOT NULL,
    TRADESPERSONID   NUMBER NOT NULL,
    RATING           NUMBER(2, 1) NOT NULL,
    FEEDBACK         VARCHAR2(255),

    CONSTRAINT FK_RATING_CUSTOMER
        FOREIGN KEY (CUSTOMERID)
        REFERENCES CUSTOMER(CUSTOMERID),

    CONSTRAINT FK_RATING_TASK
        FOREIGN KEY (TASKID)
        REFERENCES TASK(TASKID),

    CONSTRAINT FK_RATING_TRADESPERSON
        FOREIGN KEY (TRADESPERSONID)
        REFERENCES TRADESPERSON(TRADESPERSONID),

    CONSTRAINT FK_RATING_TASK_CUSTOMER
        FOREIGN KEY (TASKID, CUSTOMERID)
        REFERENCES TASK(TASKID, CUSTOMERID),

    CONSTRAINT FK_RATING_TASK_TRADE
        FOREIGN KEY (TASKID, TRADESPERSONID)
        REFERENCES BID(TASKID, TRADESPERSONID),

    CONSTRAINT CK_RATING_VALUE
        CHECK (RATING BETWEEN 1 AND 5),

    CONSTRAINT UQ_RATING_TASK_CUSTOMER
        UNIQUE (TASKID, CUSTOMERID)
);
